# **Python  Numpy**
NumPy stands for Numerical Python.

Most of the Numpy functions are written in C and C++. 
NumPy is a Python library used for working with arrays.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

It provides fetures for working in domain of linear algebra, fourier transform, and matrices.
## **Why we use Numpy:-**
In Python we have lists that serve the purpose of arrays, but they are slow to process.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.
## **When we have list then why we need Numpy?**
As we know that Python dosen't support inbuilt Array. Instead of array we work in list as a array in python.
But List is too slower than Numpy.
List Consume more storage than Numpy. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.


In [ ]:
# What to do for Work in Numpu:-
# we have to import numpy Library to implement it into the program

import numpy as np #here np means numpy object, We'll use numpy as np
# we can say that np is alais(alternate name) for Numpy

# we'll see how to create a array bu using Numpy array:- 
a = np.array([1,2,3])
print(a)


[1 2 3]


In [ ]:
#  we can check the numpy version:- 
print(np.__version__)

1.19.5


In [ ]:
 # 

# **Create a NumPy ndarray Object**
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [ ]:
# create a array 
import numpy as np
b = np.array([1,2,3,4,5])
print(b,"\n ")

# we can check the type of b
type(b)


[1 2 3 4 5] 
 


numpy.ndarray

In [ ]:
# we can define 0d - 2d - 3d - amd ND array by using Numpy:
_0d = np.array([10])
print("0D array is: \n",_0d)
_2d = np.array([[1,2,3],[4,5,6]])
print("\n\n 2d array is: \n", _2d)

_3d = np.array([[1,2,3],[1,2,23],[7,8,9]])
print("\n\n 3d array is: \n", _3d)

# n-D array
_nD = np.array([[1,2,3],[4,5,6],[7,8,90],[4,5,3],[7,5,6]])
print("\n \n The nd array is: \n", _nD)

# ***Topic*** :- Numpy array Mathematics:-

In [ ]:
# Addition 
import numpy as np
np.sum([10,20])

30

In [ ]:
## addition using Variables:-
a,b = 15,12
np.sum([a,b])

27

In [ ]:
# wanna add array in numbers by rows
np.sum([[3,2],[6,4]],axis=0)

array([9, 6])

In [ ]:
# wanna add array in numbers by columns
np.sum([[3,2],[6,4]],axis=1)

array([ 5, 10])

In [ ]:
#Subtraction of the array
import numpy as np
np.subtract(30,20)

10

In [ ]:
## subtract using Variables:-
a,b = 15,12
np.subtract(a,b)

3

In [ ]:
# Multiply two Number
np.multiply(5,20)

100

In [ ]:
np.multiply([3,2],[6,4])

array([18,  8])

In [ ]:
# Divide two numbres
np.divide(100,6)

16.666666666666668

In [ ]:
np.divide([3,2],[6,4])

array([0.5, 0.5])

In [ ]:
m =np.array([1,2,1,2])
m

array([1, 2, 1, 2])

In [ ]:
#Exponents of the array:-
np.exp(m)

array([2.71828183, 7.3890561 , 2.71828183, 7.3890561 ])

In [ ]:
#Squareroot of the array
np.sqrt(m)

array([1.        , 1.41421356, 1.        , 1.41421356])

In [ ]:
#Sin value of the array
np.sin(m)

array([0.84147098, 0.90929743, 0.84147098, 0.90929743])

In [ ]:
#Cos value of the array
np.cos(m)

array([ 0.54030231, -0.41614684,  0.54030231, -0.41614684])

In [ ]:
#Log value of the array
np.log(m)

array([0.        , 0.69314718, 0.        , 0.69314718])

In [ ]:
 # Array comparision by unsing Numpy Equal() function
a = [1,2,3]
b = [2,5,6]
c = [1,2,3]
np.equal(a,b)

array([False, False, False])

In [ ]:
# Aggregate Function:- 
a = [1,2,3]
b = [3,4,5]
print("SUM: ", np.sum(a))
print("Minimum: ", np.min(a))
print("Mean: ", np.mean(a))
print("Median: ", np.median(a))
print("Corelation Cofficient: ", np.corrcoef(a))
print("Standard Deviation: ", np.std(a))


SUM:  6
Minimum:  1
Mean:  2.0
Median:  2.0
Corelation Cofficient:  1.0
Standard Deviation:  0.816496580927726


In [ ]:
# Numpy Broadcasting:-
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([0,1,2])
print("1st Array: \n",a,"\n")
print("2nd Array: \n",b,"\n")
print("1st + 2nd Array: \n", a+b, "\n")

1st Array: 
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

2nd Array: 
 [0 1 2] 

1st + 2nd Array: 
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]] 



# **Initializing a Numpy array:-**
We can directly initialize the array:- 

In [ ]:
# initilize the array:-
# for initialize the array we use .array() functions:-
import numpy as np
a = np.array((2,3))
print(a)

#we can initializ the array with zero valo only:-
z = np.zeros((2,3))
print(" \n The array with zero values is: \n", z)

# Here we can initialize a array with same values:-
s = np.full((2,3),5)
print("\n The same value of the array is:\n",s)


[2 3]
 
 The array with zero values is: 
 [[0. 0. 0.]
 [0. 0. 0.]]

 The same value of the array is:
 [[5 5 5]
 [5 5 5]]


In [ ]:
#Arrange 1 to 50 with interval 3 by using Numpy library
import numpy as np
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
#prind the interval point by using Numpy
np.linspace(5,10,11)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
# Return the size of the array
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

#Resize the array by using ndarray.shape function.
b.shape = (3,2)
print("\n", b)


(2, 3)

 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
#create a array with 4X5
a = np.array([[1,2,3,4],[2,3,4,7],[4,5,6,8],[1,5,9,0],[1,2,4,6]])
print(a)
print("\n the size of the array is:\n",a.shape)

[[1 2 3 4]
 [2 3 4 7]
 [4 5 6 8]
 [1 5 9 0]
 [1 2 4 6]]

 the size of the array is:
 (5, 4)


In [ ]:
#resize it
a.shape = (4,5)
a

array([[1, 2, 3, 4, 2],
       [3, 4, 7, 4, 5],
       [6, 8, 1, 5, 9],
       [0, 1, 2, 4, 6]])

In [ ]:
#Check the dimension of the array by using ndim() function:- 

# reshape the Array By using reshape Operator:
d = a.reshape(10,
              2)
print("\n The reshape array is : \n", d)

print("\n\n The dimention of the array is: \n",d.ndim)




 The reshape array is : 
 [[1 2]
 [3 4]
 [2 3]
 [4 7]
 [4 5]
 [6 8]
 [1 5]
 [9 0]
 [1 2]
 [4 6]]


 The dimention of the array is: 
 2


# **Data Types in NumPy**
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
1. i - integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
9. S - string
10. U - unicode string
11. V - fixed chunk of memory for other type ( void )

In [1]:
#Check the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
# Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

### **Converting Data Type on Existing Arrays**
The best way to change the data type of an existing array, is to make a copy of the array with the **astype()** method.

The **astype()** function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [3]:
#We've Float data types and we want to convert it into in integer data types:- 
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [4]:
#Change data type from integer to boolean:

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# **Joining array by Using Numpy**
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [ ]:
# joing the 2d array together:-
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

In [5]:
#We can join the array by using stack function also:- stack()
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


# **Iterating Array:-**
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
#Iterate on the elements of the following 1-D array:

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
#Iterate on the elements of the following 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
#Iterate on each scalar element of the 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
#Iterate on the elements of the following 3-D array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x,"\n")


#Iterate down to the scalars:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

# **Iterating Arrays Using nditer()**
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

## **Iterating on Each Scalar Element**
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [ ]:
#Iterate through the following 3-D array:

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


## **Iterating Array With Different Data Types**
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [ ]:
#Iterate through the array as a string:

import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [ ]:
#Iterating With Different Step Size
#Iterate through every scalar element of the 2D array skipping 1 element:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


## **Enumerated Iteration Using ndenumerate()**
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0,) 1
(1,) 2
(2,) 3


In [ ]:
#Enumerate on following 2D array's elements:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# **Splitting NumPy Arrays**
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [6]:
# Splitting the single array into 3 parts:- 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
                         #here "arr" is array name which u want or split
newarr = np.array_split(arr, 3) # we're storing the splitting array into new array called newarr:-
                            # here 3 is the part of the splitting

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [8]:
#Access the splitted arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [9]:
# Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [10]:
#Split the 2-D array into three 2-D arrays along rows.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [11]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [12]:
#Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

# **Numpy Array manipulation**:-

In [ ]:
# Concatinate two arrays:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Stack array Row_wise_Vertically:-
np.vstack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Stack array Horizontally:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Combining Column wise :
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#Spliting Array:-
x = np.arange(16).reshape(4,4)
print(x)
print("\n ", np.hsplit(x,2))
print("\n\n", np.hsplit(x,np.array([3])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

  [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


 [array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
